### ISSUE TITLE
what's a github

### ISSUE THREAD

**Issue by ForeyIsEpic** [Piegram/PortalDebugger#1]
_**
Support Level | Skill Level required
-- | --
None | D | C | B | B+
C | D | C | C+ | B
C+ | D | D+ | C | C+
B | E+ | D | D+ | D+
B+ | E+ | E+ | D | D+
A | Any | Any | Any | Any

Support Level | Level or Stat value required
-- | --
None | 10 | 15 | 20 | 25 | 30
C | 8 | 12 | 16 | 20 | 24
C+ | 6 | 9 | 12 | 15 | 18
B | 4 | 6 | 8 | 10 | 12
B+ | 2 | 3 | 4 | 5 | 6
A | Any | Any | Any | Any | Any

**_

**Comment by Piegram** [comment]
github: you post software

that is a sentence i never thought i would say
