### ISSUE TITLE
issue 2

### ISSUE THREAD

**Issue by ForeyIsEpic** [Piegram/PortalDebugger#2]
Name | Rarity | Category | Print | Quantity
-- | -- | -- | -- | --
"Blackwing Armor Master" | Ultra Rare | Synchro Monster | New | 1
"Red Nova Dragon" | Ultra Rare | Synchro Monster | New | 1
"T.G. Wonder Magician" | Ultra Rare | Tuner&nbsp;Synchro Monster | New | 1
"Ally of Justice Catastor" | Super Rare | Synchro Monster | New | 1
"Armory Arm" | Super Rare | Synchro Monster | New | 1
"Tuning" | Super Rare | Normal&nbsp;Spell | New | 1
"Meklord Emperor Wisel" | Super Rare | Effect Monster | New | 1
"Resonator Call" | Super Rare | Normal&nbsp;Spell | New | 1
"Fortissimo the Mobile Fortress" | Super Rare | Field&nbsp;Spell | New | 1
"Old Entity Cthugua" | Super Rare | Synchro Monster | New | 1
"Yokotuner" | Super Rare | Effect&nbsp;Tuner monster | New | 1
"Stardust Wish" | Super Rare | Continuous&nbsp;Trap | New | 1
"Crimson Resonator" | Super Rare | Effect&nbsp;Tuner monster | New | 1
"Morphtronic Magnen" | Rare | Effect Monster | New | 6
"Morphtronic Boomboxen" | Rare | Effect Monster | New | 6
"Morphtronic Clocken" | Rare | Effect Monster | New | 6
"Morphtronic Boarden" | Rare | Effect Monster | New | 6
"Power Break" | Rare | Normal&nbsp;Trap | New | 6
"Meklord Fortress" | Rare | Field&nbsp;Spell | New | 6
"Meklord Army of Wisel" | Rare | Effect Monster | New | 6
"Meklord Army of Skiel" | Rare | Effect Monster | New | 6
"Meklord Army of Granel" | Rare | Effect Monster | New | 6
"The Resolute Meklord Army" | Rare | Continuous&nbsp;Spell | New | 6
"Bird of Paradise Lost" | Rare | Effect&nbsp;Tuner monster | New | 6
"Chain Resonator" | Rare | Effect&nbsp;Tuner monster | New | 6
"Red Nova" | Rare | Effect&nbsp;Tuner monster | New | 6
"Double Tool C&amp;D" | Rare | Equip&nbsp;Spell | Reprint | 6
"Drill Warrior" | Rare | Synchro Monster | Reprint | 6
"Resonant Destruction" | Rare | Continuous&nbsp;Spell | Reprint | 6
"Force Resonator" | Rare | Effect&nbsp;Tuner monster | Reprint | 6
"Turtle Bird" | Common | Normal Monster | New | 9
"Armored Starfish" | Common | Normal Monster | New | 9
"Ominous Fortunetelling" | Common | Continuous&nbsp;Trap | New | 9
"Fiend Scorpion" | Common | Normal Monster | New | 9
"Full Salvo" | Common | Normal&nbsp;Trap | New | 9
"Morphtronic Datatron" | Common | Effect Monster | New | 9
"Morphtronic Rusty Engine" | Common | Equip&nbsp;Spell | New | 9
"Ebon Arrow" | Common | Normal&nbsp;Trap | New | 9
"Black Thunder" | Common | Normal&nbsp;Trap | New | 9
"Blackwing - Etesian of Two Swords" | Common | Effect Monster | New | 9
"Boon of the Meklord Emperor" | Common | Normal&nbsp;Spell | New | 9
"Reboot" | Common | Normal&nbsp;Spell | New | 9
"Meklord Factory" | Common | Normal&nbsp;Trap | New | 9
"Spacegate" | Common | Continuous&nbsp;Trap | Reprint | 9
"Morphtronic Engine" | Common | Equip&nbsp;Spell | Reprint | 10
"Morphtronic Forcefield" | Common | Counter&nbsp;Trap | Reprint | 10
"Drill Synchron" | Common | Effect&nbsp;Tuner monster | Reprint | 9
"Creation Resonator" | Common | Effect&nbsp;Tuner monster | Reprint | 10
"Synchron Carrier" | Common | Effect Monster | Reprint | 10
"Red Supremacy" | Common | Normal&nbsp;Trap | Reprint | 10

Please fix

**Comment by ForeyIsEpic** [comment]
reply

**Comment by Piegram** [comment]
STOP

**Comment by ForeyIsEpic** [comment]
Youstill haven't finxed the sisue yet PieyIsAPie. SMH. 

- [ ] Fix it
- [ ] Amongus
- [ ] .....
